# Generated by Django 5.2.1 on 2025-06-04 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCalendarIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_access_token', models.TextField(blank=True, null=True)),
                ('google_refresh_token', models.TextField(blank=True, null=True)),
                ('google_token_expiry', models.DateTimeField(blank=True, null=True)),
                ('google_calendar_id', models.CharField(blank=True, max_length=255, null=True)),
                ('sync_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('study_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DurationField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Planned', 'Planned'), ('Completed', 'Completed'), ('Missed', 'Missed')], default='Planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('google_event_id', models.CharField(blank=True, help_text='Google Calendar event ID', max_length=255, null=True)),
                ('sync_to_google', models.BooleanField(default=False, help_text='Whether to sync this session to Google Calendar')),
                ('last_synced', models.DateTimeField(blank=True, help_text='Last time this session was synced to Google Calendar', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-study_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('reminder', 'Reminder'), ('achievement', 'Achievement'), ('system', 'System')], default='reminder', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('study_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.studysession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
