# Generated by Django 5.2.1 on 2025-06-06 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_alter_notification_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='notification_enabled',
            field=models.BooleanField(default=True, help_text='Enable notifications for this session'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='notification_message',
            field=models.TextField(blank=True, help_text='Custom notification message', null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='notification_sent',
            field=models.BooleanField(default=False, help_text='Whether notification has been sent'),
        ),
        migrations.AddField(
            model_name='studysession',
            name='notification_sent_at',
            field=models.DateTimeField(blank=True, help_text='When notification was sent', null=True),
        ),
        migrations.AddField(
            model_name='studysession',
            name='reminder_minutes',
            field=models.IntegerField(default=30, help_text='Minutes before session to send reminder'),
        ),
    ]
