# Generated by Django 5.2.1 on 2025-06-06 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_studysession_notification_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='google_notification_event_id',
            field=models.CharField(blank=True, help_text='Google Calendar notification event ID', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='ScheduledReminder',
        ),
    ]
